MvcProjeKampi/Controllers/WriterPanelController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterPanelController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult WriterProfile()
        {
            return View();
        }

        public ActionResult MyHeading()
        {
            //id = 1;
            var values = hm.GetListByWriter();
            return View(values);
        }

        [HttpGet]
        public ActionResult NewHeading()
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {

                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.vlc = valuecategory;
            return View();
        }
        [HttpPost]
        public ActionResult NewHeading(Heading p)
        {
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterID = 1;
            p.HeadingStatus = true;
            hm.HeadingAdd(p);
            return RedirectToAction("MyHeading");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.vlc = valuecategory;
            var HeadingValue = hm.GetByID(id);
            return View(HeadingValue);

        }

        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            hm.HeadingUpdate(p);
            return RedirectToAction("MyHeading");
        }

        public ActionResult DeleteHeading(int id)
        {
            var HeadingValue = hm.GetByID(id);
            hm.HeadingDelete(HeadingValue);
            return RedirectToAction("MyHeading");
        }


    }
}

MvcProjeKampi/Views/WriterPanel/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>BAŞLIK GÜNCELLEME SAYFASI</h2>
@using (Html.BeginForm("EditHeading", "WriterPanel", FormMethod.Post))
{

<div class="form-group">

    @Html.HiddenFor(x => x.HeadingID)
    @Html.HiddenFor(x => x.WriterID)
    @Html.HiddenFor(x => x.HeadingDate)
    @Html.Label("BAŞLIK ADI")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />

    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">GÜNCELLE</button>
</div>
}

MvcProjeKampi/Views/WriterPanel/MyHeading.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "MyHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">


    <section class="content">


        <div class="card">
            <div class="card-header">
                <h3 class="card-title">BAŞLIK İŞLEMLERİ</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık ADI
                            </th>
                            <th style="width: 30%">
                                YAZARI
                            </th>
                            
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>

                                    </ul>
                                </td>
                                
                                <td class="project-state">
                                    <span class="badge badge-success">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterPanel/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/WriterPanel/DeleteHeading/@item.HeadingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>


    </section>

</body>
</html>
<a href="/WriterPanel/NewHeading" class="btn btn-info">Yeni Başlık Girişi</a>

MvcProjeKampi/Views/WriterPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@using (Html.BeginForm("NewHeading", "WriterPanel", FormMethod.Post))
{

    <div class="form-group">

        @Html.Label("BAŞLIK ADI")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("KATEGORİ")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryID)
        <br />
        


        <button class="btn btn-info">BAŞLIK EKLE</button>

    </div>
}

MvcProjeKampi/Views/WriterPanel/WriterProfile.cshtml
@{
    ViewBag.Title = "WriterProfile";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>WriterProfile</h2>

merhaba